
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CATEGORYAPERTURA CATEGORYCERRADURA CERRADURA CHANNELAPERTURA CHANNELCERRADURA COPYRIGHTAPERTURA COPYRIGHTCERRADURA DESCRIPTIONAPERTURA DESCRIPTIONCERRADURA ENCODING HEIGHTAPERTURA HEIGHTCERRADURA IMAGEAPERTURA IMAGECERRADURA ITEMAPERTURA ITEMCERRADURA LINKA LINKAPERTURA LINKB LINKCERRADURA NUMERO RSSAPERTURA RSSCERRADURA TEXTO TITLEAPERTURA TITLECERRADURA URLAPERTURA URLCERRADURA VERSION WIDTHAPERTURA WIDTHCERRADURA XMLCIERRE XMLINICIOsigma : aa : xml rss xml : XMLINICIO b XMLCIERRE b : VERSIONb : VERSION ENCODING rss : RSSAPERTURA VERSION CERRADURA channel RSSCERRADURA channel : CHANNELAPERTURA contchannel CHANNELCERRADURA channel channel : CHANNELAPERTURA contchannel CHANNELCERRADURAcontchannel : title link desc itemcontchannel : title link desc opcionales itemopcionales : categoryopcionales : category copy opcionales : copy opcionales : imageopcionales : category copy image opcionales : copy image image : IMAGEAPERTURA url title link dimensiones IMAGECERRADURAdimensiones : HEIGHTAPERTURA NUMERO HEIGHTCERRADURA WIDTHAPERTURA NUMERO WIDTHCERRADURAcategory : CATEGORYAPERTURA TEXTO CATEGORYCERRADURA copy : COPYRIGHTAPERTURA TEXTO COPYRIGHTCERRADURAlink : LINKAPERTURA LINKA LINKCERRADURA link : LINKAPERTURA LINKB LINKCERRADURA title : TITLEAPERTURA TEXTO TITLECERRADURA desc : DESCRIPTIONAPERTURA TEXTO DESCRIPTIONCERRADURA url : URLAPERTURA LINKA URLCERRADURA url : URLAPERTURA LINKB URLCERRADURA item : ITEMAPERTURA contitem ITEMCERRADURA item item : ITEMAPERTURA contitem ITEMCERRADURA contitem : title link desc contitem : title link desc category '
    
_lr_action_items = {'XMLINICIO':([0,],[4,]),'$end':([1,2,5,15,],[0,-1,-2,-6,]),'RSSAPERTURA':([3,10,],[6,-3,]),'VERSION':([4,6,],[8,9,]),'XMLCIERRE':([7,8,11,],[10,-4,-5,]),'ENCODING':([8,],[11,]),'CERRADURA':([9,],[12,]),'CHANNELAPERTURA':([12,19,],[14,14,]),'RSSCERRADURA':([13,19,23,],[15,-8,-7,]),'TITLEAPERTURA':([14,31,48,62,63,],[18,18,18,-25,-26,]),'CHANNELCERRADURA':([16,29,41,51,59,],[19,-9,-10,-28,-27,]),'LINKAPERTURA':([17,28,43,56,],[21,-23,21,21,]),'TEXTO':([18,25,35,36,],[22,38,46,47,]),'DESCRIPTIONAPERTURA':([20,39,40,52,],[25,-21,-22,25,]),'LINKA':([21,49,],[26,57,]),'LINKB':([21,49,],[27,58,]),'TITLECERRADURA':([22,],[28,]),'ITEMAPERTURA':([24,30,32,33,34,44,45,50,51,53,54,55,67,],[31,31,-11,-13,-14,-12,-16,-24,31,-15,-19,-20,-17,]),'CATEGORYAPERTURA':([24,50,60,],[35,-24,35,]),'COPYRIGHTAPERTURA':([24,32,50,54,],[36,36,-24,-19,]),'IMAGEAPERTURA':([24,33,44,50,55,],[37,37,37,-24,-20,]),'LINKCERRADURA':([26,27,],[39,40,]),'URLAPERTURA':([37,],[49,]),'DESCRIPTIONCERRADURA':([38,],[50,]),'HEIGHTAPERTURA':([39,40,61,],[-21,-22,66,]),'ITEMCERRADURA':([42,50,54,60,64,],[51,-24,-19,-29,-30,]),'CATEGORYCERRADURA':([46,],[54,]),'COPYRIGHTCERRADURA':([47,],[55,]),'URLCERRADURA':([57,58,],[62,63,]),'IMAGECERRADURA':([65,72,],[67,-18,]),'NUMERO':([66,70,],[68,71,]),'HEIGHTCERRADURA':([68,],[69,]),'WIDTHAPERTURA':([69,],[70,]),'WIDTHCERRADURA':([71,],[72,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'sigma':([0,],[1,]),'a':([0,],[2,]),'xml':([0,],[3,]),'rss':([3,],[5,]),'b':([4,],[7,]),'channel':([12,19,],[13,23,]),'contchannel':([14,],[16,]),'title':([14,31,48,],[17,43,56,]),'link':([17,43,56,],[20,52,61,]),'desc':([20,52,],[24,60,]),'item':([24,30,51,],[29,41,59,]),'opcionales':([24,],[30,]),'category':([24,60,],[32,64,]),'copy':([24,32,],[33,44,]),'image':([24,33,44,],[34,45,53,]),'contitem':([31,],[42,]),'url':([37,],[48,]),'dimensiones':([61,],[65,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> sigma","S'",1,None,None,None),
  ('sigma -> a','sigma',1,'p_sigma','AnalizadorSintactico.py',22),
  ('a -> xml rss','a',2,'p_a','AnalizadorSintactico.py',26),
  ('xml -> XMLINICIO b XMLCIERRE','xml',3,'p_xml','AnalizadorSintactico.py',32),
  ('b -> VERSION','b',1,'p_b1','AnalizadorSintactico.py',36),
  ('b -> VERSION ENCODING','b',2,'p_b2','AnalizadorSintactico.py',40),
  ('rss -> RSSAPERTURA VERSION CERRADURA channel RSSCERRADURA','rss',5,'p_rss','AnalizadorSintactico.py',46),
  ('channel -> CHANNELAPERTURA contchannel CHANNELCERRADURA channel','channel',4,'p_channel1','AnalizadorSintactico.py',50),
  ('channel -> CHANNELAPERTURA contchannel CHANNELCERRADURA','channel',3,'p_channel2','AnalizadorSintactico.py',54),
  ('contchannel -> title link desc item','contchannel',4,'p_contchannel1','AnalizadorSintactico.py',58),
  ('contchannel -> title link desc opcionales item','contchannel',5,'p_contchannel2','AnalizadorSintactico.py',62),
  ('opcionales -> category','opcionales',1,'p_opcionales1','AnalizadorSintactico.py',66),
  ('opcionales -> category copy','opcionales',2,'p_opcionales2','AnalizadorSintactico.py',70),
  ('opcionales -> copy','opcionales',1,'p_opcionales3','AnalizadorSintactico.py',74),
  ('opcionales -> image','opcionales',1,'p_opcionales4','AnalizadorSintactico.py',78),
  ('opcionales -> category copy image','opcionales',3,'p_opcionales5','AnalizadorSintactico.py',82),
  ('opcionales -> copy image','opcionales',2,'p_opcionales6','AnalizadorSintactico.py',86),
  ('image -> IMAGEAPERTURA url title link dimensiones IMAGECERRADURA','image',6,'p_image','AnalizadorSintactico.py',90),
  ('dimensiones -> HEIGHTAPERTURA NUMERO HEIGHTCERRADURA WIDTHAPERTURA NUMERO WIDTHCERRADURA','dimensiones',6,'p_dimensiones','AnalizadorSintactico.py',94),
  ('category -> CATEGORYAPERTURA TEXTO CATEGORYCERRADURA','category',3,'p_category','AnalizadorSintactico.py',98),
  ('copy -> COPYRIGHTAPERTURA TEXTO COPYRIGHTCERRADURA','copy',3,'p_copy','AnalizadorSintactico.py',102),
  ('link -> LINKAPERTURA LINKA LINKCERRADURA','link',3,'p_link1','AnalizadorSintactico.py',106),
  ('link -> LINKAPERTURA LINKB LINKCERRADURA','link',3,'p_link2','AnalizadorSintactico.py',110),
  ('title -> TITLEAPERTURA TEXTO TITLECERRADURA','title',3,'p_title','AnalizadorSintactico.py',114),
  ('desc -> DESCRIPTIONAPERTURA TEXTO DESCRIPTIONCERRADURA','desc',3,'p_desc','AnalizadorSintactico.py',118),
  ('url -> URLAPERTURA LINKA URLCERRADURA','url',3,'p_url1','AnalizadorSintactico.py',122),
  ('url -> URLAPERTURA LINKB URLCERRADURA','url',3,'p_url2','AnalizadorSintactico.py',126),
  ('item -> ITEMAPERTURA contitem ITEMCERRADURA item','item',4,'p_item1','AnalizadorSintactico.py',130),
  ('item -> ITEMAPERTURA contitem ITEMCERRADURA','item',3,'p_item2','AnalizadorSintactico.py',134),
  ('contitem -> title link desc','contitem',3,'p_contitem1','AnalizadorSintactico.py',138),
  ('contitem -> title link desc category','contitem',4,'p_contitem2','AnalizadorSintactico.py',142),
]
