
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CATEGORYAPERTURA CATEGORYCERRADURA CERRADURA CHANNELAPERTURA CHANNELCERRADURA COPYRIGHTAPERTURA COPYRIGHTCERRADURA DESCRIPTIONAPERTURA DESCRIPTIONCERRADURA ENCODING FTP FTPS HEIGHTAPERTURA HEIGHTCERRADURA HTTP HTTPS IMAGEAPERTURA IMAGECERRADURA ITEMAPERTURA ITEMCERRADURA LINK LINKAPERTURA LINKCERRADURA NUMERO RANGOH RANGOW RSSAPERTURA RSSCERRADURA TEXTO TITLEAPERTURA TITLECERRADURA URLAPERTURA URLCERRADURA VERSION WIDTHAPERTURA WIDTHCERRADURA XMLCIERRE XMLINICIOsigma : aa : xml rss xml : XMLINICIO b XMLCIERRE b : VERSIONb : VERSION ENCODING rss : RSSAPERTURA VERSION CERRADURA channel RSSCERRADURA channel : CHANNELAPERTURA contchannel CHANNELCERRADURA channel channel : CHANNELAPERTURA contchannel CHANNELCERRADURAcontchannel : title link desc itemcontchannel : title link desc opcionales itemopcionales : categoryopcionales : category copy opcionales : copy opcionales : imageopcionales : category copy image opcionales : copy image image : IMAGEAPERTURA url title link dimensiones IMAGECERRADURAdimensiones : HEIGHTAPERTURA RANGOH HEIGHTCERRADURA WIDTHAPERTURA RANGOW WIDTHCERRADURAcategory : CATEGORYAPERTURA TEXTO CATEGORYCERRADURA copy : COPYRIGHTAPERTURA TEXTO COPYRIGHTCERRADURAlink : LINKAPERTURA HTTP LINK LINKCERRADURA link : LINKAPERTURA HTTPS LINK LINKCERRADURA link : LINKAPERTURA FTP LINK LINKCERRADURA link : LINKAPERTURA FTPS LINK LINKCERRADURA title : TITLEAPERTURA TEXTO TITLECERRADURA desc : DESCRIPTIONAPERTURA TEXTO DESCRIPTIONCERRADURA url : URLAPERTURA HTTP LINK URLCERRADURA url : URLAPERTURA HTTPS LINK URLCERRADURA url : URLAPERTURA FTP LINK URLCERRADURA url : URLAPERTURA FTPS LINK URLCERRADURA item : ITEMAPERTURA contitem ITEMCERRADURA item item : ITEMAPERTURA contitem ITEMCERRADURA contitem : title link desc contitem : title link desc category '
    
_lr_action_items = {'XMLINICIO':([0,],[4,]),'$end':([1,2,5,15,],[0,-1,-2,-6,]),'RSSAPERTURA':([3,10,],[6,-3,]),'VERSION':([4,6,],[8,9,]),'XMLCIERRE':([7,8,11,],[10,-4,-5,]),'ENCODING':([8,],[11,]),'CERRADURA':([9,],[12,]),'CHANNELAPERTURA':([12,19,],[14,14,]),'RSSCERRADURA':([13,19,23,],[15,-8,-7,]),'TITLEAPERTURA':([14,33,52,79,80,81,82,],[18,18,18,-27,-28,-29,-30,]),'CHANNELCERRADURA':([16,31,45,59,69,],[19,-9,-10,-32,-31,]),'LINKAPERTURA':([17,30,47,64,],[21,-25,21,21,]),'TEXTO':([18,25,37,38,],[22,40,50,51,]),'DESCRIPTIONAPERTURA':([20,55,56,57,58,60,],[25,-21,-22,-23,-24,25,]),'HTTP':([21,53,],[26,65,]),'HTTPS':([21,53,],[27,66,]),'FTP':([21,53,],[28,67,]),'FTPS':([21,53,],[29,68,]),'TITLECERRADURA':([22,],[30,]),'ITEMAPERTURA':([24,32,34,35,36,48,49,54,59,61,62,63,83,],[33,33,-11,-13,-14,-12,-16,-26,33,-15,-19,-20,-17,]),'CATEGORYAPERTURA':([24,54,70,],[37,-26,37,]),'COPYRIGHTAPERTURA':([24,34,54,62,],[38,38,-26,-19,]),'IMAGEAPERTURA':([24,35,48,54,63,],[39,39,39,-26,-20,]),'LINK':([26,27,28,29,65,66,67,68,],[41,42,43,44,72,73,74,75,]),'URLAPERTURA':([39,],[53,]),'DESCRIPTIONCERRADURA':([40,],[54,]),'LINKCERRADURA':([41,42,43,44,],[55,56,57,58,]),'ITEMCERRADURA':([46,54,62,70,76,],[59,-26,-19,-33,-34,]),'CATEGORYCERRADURA':([50,],[62,]),'COPYRIGHTCERRADURA':([51,],[63,]),'HEIGHTAPERTURA':([55,56,57,58,71,],[-21,-22,-23,-24,78,]),'URLCERRADURA':([72,73,74,75,],[79,80,81,82,]),'IMAGECERRADURA':([77,88,],[83,-18,]),'RANGOH':([78,],[84,]),'HEIGHTCERRADURA':([84,],[85,]),'WIDTHAPERTURA':([85,],[86,]),'RANGOW':([86,],[87,]),'WIDTHCERRADURA':([87,],[88,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'sigma':([0,],[1,]),'a':([0,],[2,]),'xml':([0,],[3,]),'rss':([3,],[5,]),'b':([4,],[7,]),'channel':([12,19,],[13,23,]),'contchannel':([14,],[16,]),'title':([14,33,52,],[17,47,64,]),'link':([17,47,64,],[20,60,71,]),'desc':([20,60,],[24,70,]),'item':([24,32,59,],[31,45,69,]),'opcionales':([24,],[32,]),'category':([24,70,],[34,76,]),'copy':([24,34,],[35,48,]),'image':([24,35,48,],[36,49,61,]),'contitem':([33,],[46,]),'url':([39,],[52,]),'dimensiones':([71,],[77,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> sigma","S'",1,None,None,None),
  ('sigma -> a','sigma',1,'p_sigma','AnalizadorSintactico.py',22),
  ('a -> xml rss','a',2,'p_a','AnalizadorSintactico.py',26),
  ('xml -> XMLINICIO b XMLCIERRE','xml',3,'p_xml','AnalizadorSintactico.py',32),
  ('b -> VERSION','b',1,'p_b1','AnalizadorSintactico.py',36),
  ('b -> VERSION ENCODING','b',2,'p_b2','AnalizadorSintactico.py',40),
  ('rss -> RSSAPERTURA VERSION CERRADURA channel RSSCERRADURA','rss',5,'p_rss','AnalizadorSintactico.py',46),
  ('channel -> CHANNELAPERTURA contchannel CHANNELCERRADURA channel','channel',4,'p_channel1','AnalizadorSintactico.py',50),
  ('channel -> CHANNELAPERTURA contchannel CHANNELCERRADURA','channel',3,'p_channel2','AnalizadorSintactico.py',54),
  ('contchannel -> title link desc item','contchannel',4,'p_contchannel1','AnalizadorSintactico.py',58),
  ('contchannel -> title link desc opcionales item','contchannel',5,'p_contchannel2','AnalizadorSintactico.py',62),
  ('opcionales -> category','opcionales',1,'p_opcionales1','AnalizadorSintactico.py',66),
  ('opcionales -> category copy','opcionales',2,'p_opcionales2','AnalizadorSintactico.py',70),
  ('opcionales -> copy','opcionales',1,'p_opcionales3','AnalizadorSintactico.py',74),
  ('opcionales -> image','opcionales',1,'p_opcionales4','AnalizadorSintactico.py',78),
  ('opcionales -> category copy image','opcionales',3,'p_opcionales5','AnalizadorSintactico.py',82),
  ('opcionales -> copy image','opcionales',2,'p_opcionales6','AnalizadorSintactico.py',86),
  ('image -> IMAGEAPERTURA url title link dimensiones IMAGECERRADURA','image',6,'p_image','AnalizadorSintactico.py',90),
  ('dimensiones -> HEIGHTAPERTURA RANGOH HEIGHTCERRADURA WIDTHAPERTURA RANGOW WIDTHCERRADURA','dimensiones',6,'p_dimensiones','AnalizadorSintactico.py',94),
  ('category -> CATEGORYAPERTURA TEXTO CATEGORYCERRADURA','category',3,'p_category','AnalizadorSintactico.py',98),
  ('copy -> COPYRIGHTAPERTURA TEXTO COPYRIGHTCERRADURA','copy',3,'p_copy','AnalizadorSintactico.py',102),
  ('link -> LINKAPERTURA HTTP LINK LINKCERRADURA','link',4,'p_link1','AnalizadorSintactico.py',106),
  ('link -> LINKAPERTURA HTTPS LINK LINKCERRADURA','link',4,'p_link2','AnalizadorSintactico.py',110),
  ('link -> LINKAPERTURA FTP LINK LINKCERRADURA','link',4,'p_link3','AnalizadorSintactico.py',114),
  ('link -> LINKAPERTURA FTPS LINK LINKCERRADURA','link',4,'p_link4','AnalizadorSintactico.py',118),
  ('title -> TITLEAPERTURA TEXTO TITLECERRADURA','title',3,'p_title','AnalizadorSintactico.py',122),
  ('desc -> DESCRIPTIONAPERTURA TEXTO DESCRIPTIONCERRADURA','desc',3,'p_desc','AnalizadorSintactico.py',126),
  ('url -> URLAPERTURA HTTP LINK URLCERRADURA','url',4,'p_url1','AnalizadorSintactico.py',130),
  ('url -> URLAPERTURA HTTPS LINK URLCERRADURA','url',4,'p_url2','AnalizadorSintactico.py',134),
  ('url -> URLAPERTURA FTP LINK URLCERRADURA','url',4,'p_url3','AnalizadorSintactico.py',138),
  ('url -> URLAPERTURA FTPS LINK URLCERRADURA','url',4,'p_url4','AnalizadorSintactico.py',142),
  ('item -> ITEMAPERTURA contitem ITEMCERRADURA item','item',4,'p_item1','AnalizadorSintactico.py',146),
  ('item -> ITEMAPERTURA contitem ITEMCERRADURA','item',3,'p_item2','AnalizadorSintactico.py',150),
  ('contitem -> title link desc','contitem',3,'p_contitem1','AnalizadorSintactico.py',154),
  ('contitem -> title link desc category','contitem',4,'p_contitem2','AnalizadorSintactico.py',158),
]
